config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landings#index'
  resources :landings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/landing.rb
class Landing < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  	@landing = Landing.order("RANDOM()").first
  end

  def new
  	@landing = Landing.new
  end

  def create
  	Landing.create(landing_params)
  	redirect_to root_path
  end

  private

  def landing_params
  	params.require(:landing).permit(:quote, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/index.html.erb
<div class="quiz-box text-center">
	<h1>Quotes For All From All<h1>
	<% if @landing != nil %>
		<h2><%= @landing.quote %></h2>
		<h3>- <%= @landing.author %></h3>
	<% else %>
		<h2>There aren't any quotes yet D:</h2>
		<%= link_to 'Add a quote', new_landing_path , class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/landings/new.html.erb
<div class="quiz-box">
	<h1>Enter Your Quote</h1>
	<%= simple_form_for @landing do |f| %>
		<%= f.input :quote %>
		<%= f.input :author %>
		<br />
		<%= f.submit 'Create', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <%= link_to 'Quizical', root_path, class: 'navbar-brand' %>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to new_landing_path, class: 'nav-link' do %>
              Add a Quote
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>